### ISSUE TITLE
Functionality to challenge other players directly

### ISSUE THREAD

**Issue by theevenprime2** [yangez/go-meteor#100]
related to #78 and #79

It would be nice if player A can challenge player B by right clicking on player B's name and selecting "Challenge" and then setting some match details.  Can also add a choice to make it for rating points or not.  A further extension on this is betting points or some other currency -- "play money", avatars, whatever fun stuff, i.e. in CSGO you can bet your skins on pro matches (not sure if this has a place in the go community, but yeah).
Player B gets a notification to accept with all of the above details (match length, board size, etc).

Possibly do a "best of" series, too.

**Comment by yangez** [comment]
For now, I'll enable users to challenge other users that exist in the system.
* If they're not on the app, email them a notification
* If they are present on the app, do browser notification + in-app popup
* Accept - join the game immediately on both sides. Challenger gets similar notification that the person joined.
* Decline - challenger gets notification person declined. Challenge gets canceled.

Follow-up: implement an email address input that allows people to challenge people *not* on the app. (Later can implement facebook friends, etc.) Sends them an email that invites them to expedited signup and sends them immediately to the game.

**Comment by yangez** [comment]
Shit, we actually need their email addresses first to do this. I'll finish implementing #59 first before tackling this issue.
