### ISSUE TITLE
Retry button after match ends

### ISSUE THREAD

**Issue by theevenprime2** [yangez/go-meteor#101]
After a game is finished, players should have a button to request to play another game with the same person while on the board screen.

**Comment by voxlol** [comment]
Good idea!

**Comment by yangez** [comment]
Maybe we can do this by implementing the "challenges" feature, and then just having the "Rematch" issue a specific challenge with pre-filled options.

**Comment by yangez** [comment]
Let's do this with a popup announcing who won immediately after the game, and then giving players the opportunity to rematch here. (Clicking Rematch will just send a challenge to the player with the same game settings.)
