### ISSUE TITLE
Implement global chat

### ISSUE THREAD

**Issue by voxlol** [yangez/go-meteor#11]
Add chatrooms, lobbies, private messaging. Maybe also add in some Facebook / Twitter integration.

**Comment by yangez** [comment]
Shit man this should be split into several different issues:

* Private messaging
* Determine who's online
* Global chat 
* Segment global chant into different chatrooms
* Twitter/Facebook authentication

This is too huge for a single issue...

**Comment by voxlol** [comment]
yea gg

**Comment by yangez** [comment]
Global chat includes:
* See who's online
* be able to talk to everyone

**Comment by yangez** [comment]
Also should have a global users list.
