### ISSUE TITLE
Challenge Mode Bug

### ISSUE THREAD

**Issue by voxlol** [yangez/go-meteor#127]
![bug](https://cloud.githubusercontent.com/assets/11891171/9000655/9602da36-3710-11e5-919b-1cf75065f0c5.png)

- allenlol challenged mindeavor to a 19x19 no time match.
- mindeavor accepted, and no game was created

I received the bug featured in my console.

**Comment by yangez** [comment]
Hmm I can't seem to recreate this locally. Did you click the green "arrow" button after mindeavor accepted? That's the only place the `challenge/acknowledge` gets called, and it's not supposed to impede the creation of a game.
