### ISSUE TITLE
Implement time controls

### ISSUE THREAD

**Issue by voxlol** [yangez/go-meteor#17]
Should have the ability to close a match if the opponent hasn't made a movie in a "while"

OR

Should have the ability to hide those matches away to some other place

**Comment by yangez** [comment]
When we implement time controls this should be taken care of.

**Comment by yangez** [comment]
Will be implementing time controls. Will also have the option to not specify any time controls for now, for an untimed "casual" game.

We can have longer time controls for correspondence-style games, or shorter time controls for single-sitting games, and even shorter ones for blitz games.
