### ISSUE TITLE
Create real domain name + hosting for site

### ISSUE THREAD

**Issue by yangez** [yangez/go-meteor#98]
This way, when we send people to the site, it'll be on our own domain name instead of Meteor's (which goes down periodically)

**Comment by voxlol** [comment]
I'm down to pitch in for any costs. Personally, I'd like to get a *.io domain cause IO domains are badass

**Comment by theevenprime2** [comment]
Should totally use *.sexy

**Comment by yangez** [comment]
Gonna make one with onlinego.net for the SEO benefits :)
